apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhrigu-guest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhrigu-guest
  template:
    metadata:
      labels:
        app: bhrigu-guest
    spec:
      containers:
      - name: bhrigu-guest
        image: ${DOCKER_HUB_USERNAME}/bhrigu-guest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PRO_SERVICE_URL
          value: "http://bhrigu-pro:5001"
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        - name: models-volume
          mountPath: /app/models
        - name: reports-volume
          mountPath: /app/reports
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: bhrigu-guest-uploads-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: bhrigu-guest-models-pvc
      - name: reports-volume
        persistentVolumeClaim:
          claimName: bhrigu-guest-reports-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhrigu-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhrigu-pro
  template:
    metadata:
      labels:
        app: bhrigu-pro
    spec:
      containers:
      - name: bhrigu-pro
        image: ${DOCKER_HUB_USERNAME}/bhrigu-pro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: GUEST_SERVICE_URL
          value: "http://bhrigu-guest:5000"
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        - name: models-volume
          mountPath: /app/models
        - name: reports-volume
          mountPath: /app/reports
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: bhrigu-pro-uploads-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: bhrigu-pro-models-pvc
      - name: reports-volume
        persistentVolumeClaim:
          claimName: bhrigu-pro-reports-pvc