apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhrigu-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhrigu-guest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhrigu-guest
  template:
    metadata:
      labels:
        app: bhrigu-guest
    spec:
      containers:
      - name: bhrigu-guest
        image: sujayvk/bhrigu-guest:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "run.py"
        - name: FLASK_ENV
          value: "development"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bhrigu-secrets
              key: gemini-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: instance-data
          mountPath: /app/instance
        - name: uploads-data
          mountPath: /app/uploads
        - name: models-data
          mountPath: /app/models
        - name: reports-data
          mountPath: /app/reports
      volumes:
      - name: instance-data
        persistentVolumeClaim:
          claimName: instance-pvc
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: models-data
        persistentVolumeClaim:
          claimName: models-pvc
      - name: reports-data
        persistentVolumeClaim:
          claimName: reports-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bhrigu-guest-service
spec:
  type: ClusterIP
  selector:
    app: bhrigu-guest
  ports:
    - port: 80
      targetPort: 5000