apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bhrigu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: bhrigu.local  # Add this to your hosts file for local development
    http:
      paths:
      - path: /guest(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bhrigu-guest
            port:
              number: 5000
      - path: /pro(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bhrigu-pro
            port:
              number: 5001
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: bhrigu-guest
            port:
              number: 5000