"""Add API fields to ProModelRun

Revision ID: 158c156d4de7
Revises: 
Create Date: 2025-05-04 22:10:44.426336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158c156d4de7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro_model_runs', sa.Column('api_endpoint', sa.String(length=255), nullable=True))
    op.add_column('pro_model_runs', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pro_model_runs', 'api_key')
    op.drop_column('pro_model_runs', 'api_endpoint')
    # ### end Alembic commands ###
