---
- name: Deploy Bhrigu Guest Mode to Kubernetes
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Apply PVCs
      shell: kubectl apply -f ../k8s/pvcs.yaml --validate=false
      ignore_errors: yes
      
    - name: Apply Secret
      shell: kubectl apply -f ../k8s/secrets.yaml --validate=false
      ignore_errors: yes
      
    - name: Apply Deployment
      shell: kubectl apply -f ../k8s/deployment.yaml --validate=false
      ignore_errors: yes
      
    - name: Apply Ingress
      shell: kubectl apply -f ../k8s/ingress.yaml --validate=false
      ignore_errors: yes
      
    - name: Wait for deployment to be ready
      shell: kubectl rollout status deployment/bhrigu-guest --timeout=300s
      ignore_errors: yes