---
- name: Deploy Bhrigu Guest Mode to Kubernetes
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Apply PVCs
      shell: kubectl apply -f k8s/pvcs.yaml
      
    - name: Apply Secret
      shell: kubectl apply -f k8s/secrets.yaml
      
    - name: Apply Deployment
      shell: kubectl apply -f k8s/deployment.yaml
      
    - name: Apply Ingress
      shell: kubectl apply -f k8s/ingress.yaml
      
    - name: Wait for deployment to be ready
      shell: kubectl rollout status deployment/bhrigu-guest --timeout=300s
      register: rollout_result
      failed_when: rollout_result.rc != 0
      
    - name: Check service status
      shell: kubectl get service bhrigu-guest-service
      register: service_result
      
    - name: Display service information
      debug:
        msg: "Service is available at: {{ service_result.stdout }}"