name: CI/CD Pipeline for Bhrigu.ai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sujayvk/bhrigu-guest:latest

    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup Minikube
      if: github.event_name == 'pull_request'
      uses: medyagh/setup-minikube@master

    - name: Deploy to Minikube for PR validation
      if: github.event_name == 'pull_request'
      run: |
        minikube start
        kubectl apply -f k8s/pvcs.yaml
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl rollout status deployment/bhrigu-guest --timeout=120s

    - name: Deploy to production with Ansible
      if: github.event_name == 'push'
      run: ansible-playbook ansible/deploy.yml