name: CI/CD Pipeline for Bhrigu.ai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sujayvk/bhrigu-guest:latest

    - name: Setup Minikube
      uses: medyagh/setup-minikube@master
      
    - name: Wait for Minikube to start
      run: |
        minikube status
        kubectl get nodes

    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Deploy with Ansible
      run: ansible-playbook ansible/deploy.yml
      
    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get services
        minikube service list